name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MYSQL_DATABASE: inventivIT
  MYSQL_USER: asmaa123
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: root
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  SERVER_PORT: 8083

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker images
        run: docker-compose build