name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
  MYSQL_USER: ${{ env.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  SERVER_PORT: 8083
  SPRING_PROFILES_ACTIVE: test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: |
          mvn clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{ env.MYSQL_DATABASE }}
          SPRING_DATASOURCE_USERNAME: ${{ env.MYSQL_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.MYSQL_PASSWORD }}

      - name: Build Package
        if: success()
        run: mvn package -DskipTests

      - name: Build Docker images
        if: success()
        run: docker compose build